---
- name: Example Playbook

  hosts: cassandra

  remote_user: root

  vars:
    cassandra_repo_apache_release: 311x
    cassandra_systemd_enabled: true
    cassandra_configure_apache_repo: true
    cassandra_cluster_name: TestCluster
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/commitlog
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
    cassandra_regex_replacements:
      - path: cassandra-env.sh
        line: 'MAX_HEAP_SIZE="256M"'
        regexp: '^#MAX_HEAP_SIZE="4G"'
      - path: cassandra-env.sh
        line: 'HEAP_NEWSIZE="100M"'
        regexp: '^#HEAP_NEWSIZE="800M"'
      - path: cassandra-rackdc.properties
        line: 'dc=DC1'
        regexp: '^dc='
      - path: cassandra-rackdc.properties
        line: 'rack=RACK1'
        regexp: '^rack='
    cassandra_configuration:
      authenticator: PasswordAuthenticator
      cluster_name: "{{ cassandra_cluster_name }}"
      commitlog_directory: /data/cassandra/commitlog
      commitlog_sync: periodic
      commitlog_sync_period_in_ms: 10000
      data_file_directories:
        - /data/cassandra/data
      endpoint_snitch: GossipingPropertyFileSnitch
      hints_directory: "/data/cassandra/hints"
      listen_address: "{{ ansible_default_ipv4.address }}"
      partitioner: org.apache.cassandra.dht.Murmur3Partitioner
      saved_caches_directory: /data/cassandra/saved_caches
      seed_provider:
        - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
          parameters:
            - seeds: "{{ cassandra_seed }}"
      start_native_transport: true

  roles:
    - role: ansible_cassandra

  post_tasks:
    - name: Wait for the Cassandra Listener
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 9042
      when: not ansible_check_mode

    - name: Wait for the Cassandra to Gossip
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 9160
      when: not ansible_check_mode

    - name: Wait for the Cassandra Service to be Running
      service_facts:
      retries: 100
      delay: 3
      register: cassandra_services_facts
      until: cassandra_services_facts.ansible_facts.services['cassandra.service'].state == 'running'
      when:
        - not ansible_check_mode
