---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -ex
  yamllint -s .
  ansible-lint

platforms:
  - name: node0
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    groups:
      - cassandra
      - cassandra_clustered
      - cassandra_seed

  - name: node1
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    groups:
      - cassandra
      - cassandra_clustered
      - cassandra_seed

  - name: node2
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    groups:
      - cassandra
      - cassandra_clustered

  - name: node3
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    groups:
      - cassandra
      - cassandra_clustered

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"
  inventory:
    group_vars:
      centos8:
        ansible_python_interpreter: python3
  log: True
  options:
    v: 1

scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify

verifier:
  name: testinfra
  options:
    connection: docker
    durations: 3
    v: 1
