---
- hosts: all

  remote_user: root

  vars:
    instance_key: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
    packages:
      CentOS7:
        - initscripts
        - iproute
      CentOS8:
        - initscripts
        - iproute
        - java-1.8.0-openjdk-headless
    instance_info:
      ansible_python_interpreter: "{{ ansible_python_interpreter | default('python') }}"
      ansible_distribution: "{{ ansible_distribution }}"
      ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"
      ansible_os_family: "{{ ansible_os_family }}"
      cassandra_service_restart: "{{ cassandra_service_restart | default(True) }}"
      cassandra_systemd_enabled: "{{ cassandra_systemd_enabled | default(False) }}"

  tasks:
    - name: Display Host Information
      debug:
        var: instance_info

    - name: Install EPEL for CentOS 7
      package:
        name: epel-release
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded

    - name: Install RedHat Packages
      package:
        name: "{{ packages[instance_key] }}"
      delay: 10
      register: pkgstatus
      retries: 5
      until: pkgstatus is succeeded
